<?php

namespace Database\Seeders;

use App\Models\StudentProfile;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        $students = [
            [
                'name' => 'محمود علي',
                'email' => 'student-demo-01@computiq.test',
                'phone' => '+964-770-100-0001',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Baghdad',
                    'department' => 'Computer Science',
                    'degree' => 'BSc',
                    'start_year' => 2021,
                    'graduation_year' => 2025,
                    'academic_status' => 'Senior',
                    'headline' => 'Frontend Developer',
                    'short_bio' => 'مهتم بتطوير الواجهات وتجربة المستخدم وبناء منتجات تعليمية.',
                    'city' => 'Baghdad',
                    'country' => 'Iraq',
                    'preferred_role' => 'Frontend Developer',
                    'preferred_city' => 'Baghdad',
                    'job_available' => true,
                    'internship_available' => true,
                    'linkedin_url' => 'https://linkedin.com/in/mahmoud-ali-computiq',
                    'github_url' => 'https://github.com/mahmoud-ali-computiq',
                    'portfolio_url' => 'https://mahmoud-ali-computiq.test',
                    'skills' => ['React', 'TypeScript', 'Tailwind CSS'],
                    'projects' => ['LMS dashboard', 'E-commerce UI'],
                ],
            ],
            [
                'name' => 'عبدالله حسين',
                'email' => 'student-demo-02@computiq.test',
                'phone' => '+964-770-100-0002',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Mosul',
                    'department' => 'Software Engineering',
                    'degree' => 'BSc',
                    'start_year' => 2020,
                    'graduation_year' => 2024,
                    'academic_status' => 'Graduate',
                    'headline' => 'Backend Developer',
                    'short_bio' => 'أركّز على Laravel وبناء APIs ونظم المدفوعات.',
                    'city' => 'Mosul',
                    'country' => 'Iraq',
                    'preferred_role' => 'Backend Developer',
                    'preferred_city' => 'Erbil',
                    'job_available' => true,
                    'internship_available' => false,
                    'linkedin_url' => 'https://linkedin.com/in/abdullah-hussein-computiq',
                    'github_url' => 'https://github.com/abdullah-hussein-computiq',
                    'portfolio_url' => 'https://abdullah-hussein-computiq.test',
                    'skills' => ['Laravel', 'MySQL', 'REST APIs'],
                    'projects' => ['Payment gateway integration', 'Course analytics API'],
                ],
            ],
            [
                'name' => 'يوسف إبراهيم',
                'email' => 'student-demo-03@computiq.test',
                'phone' => '+964-770-100-0003',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'Salahaddin University',
                    'department' => 'Information Technology',
                    'degree' => 'BSc',
                    'start_year' => 2022,
                    'graduation_year' => 2026,
                    'academic_status' => 'Junior',
                    'headline' => 'AI Enthusiast',
                    'short_bio' => 'أتعلم الذكاء الاصطناعي وتحليل البيانات وأحب التجارب العملية.',
                    'city' => 'Erbil',
                    'country' => 'Iraq',
                    'preferred_role' => 'Data Analyst',
                    'preferred_city' => 'Erbil',
                    'job_available' => false,
                    'internship_available' => true,
                    'linkedin_url' => 'https://linkedin.com/in/yousef-ibrahim-computiq',
                    'github_url' => 'https://github.com/yousef-ibrahim-computiq',
                    'portfolio_url' => 'https://yousef-ibrahim-computiq.test',
                    'skills' => ['Python', 'Pandas', 'Data Visualization'],
                    'projects' => ['Student retention predictor', 'Power BI dashboards'],
                ],
            ],
            [
                'name' => 'سلمى كريم',
                'email' => 'student-demo-04@computiq.test',
                'phone' => '+964-770-100-0004',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Basrah',
                    'department' => 'Graphic Design',
                    'degree' => 'BFA',
                    'start_year' => 2021,
                    'graduation_year' => 2025,
                    'academic_status' => 'Senior',
                    'headline' => 'UI Designer',
                    'short_bio' => 'أحب تصميم المنتجات الرقمية والهويات البصرية وتجارب المستخدم.',
                    'city' => 'Basrah',
                    'country' => 'Iraq',
                    'preferred_role' => 'UI Designer',
                    'preferred_city' => 'Baghdad',
                    'job_available' => true,
                    'internship_available' => true,
                    'linkedin_url' => 'https://linkedin.com/in/salma-karim-computiq',
                    'github_url' => 'https://github.com/salma-karim-computiq',
                    'portfolio_url' => 'https://salma-karim-computiq.test',
                    'skills' => ['Figma', 'Design Systems', 'Branding'],
                    'projects' => ['Mobile banking UI', 'Academy design system'],
                ],
            ],
            [
                'name' => 'ريم خالد',
                'email' => 'student-demo-05@computiq.test',
                'phone' => '+964-770-100-0005',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Baghdad',
                    'department' => 'Business Administration',
                    'degree' => 'BBA',
                    'start_year' => 2020,
                    'graduation_year' => 2024,
                    'academic_status' => 'Graduate',
                    'headline' => 'Digital Marketing Specialist',
                    'short_bio' => 'أطبّق حملات تسويق رقمي عملية وأحلل الأداء باستمرار.',
                    'city' => 'Baghdad',
                    'country' => 'Iraq',
                    'preferred_role' => 'Performance Marketer',
                    'preferred_city' => 'Baghdad',
                    'job_available' => true,
                    'internship_available' => false,
                    'linkedin_url' => 'https://linkedin.com/in/reem-khalid-computiq',
                    'github_url' => 'https://github.com/reem-khalid-computiq',
                    'portfolio_url' => 'https://reem-khalid-computiq.test',
                    'skills' => ['Google Ads', 'Meta Ads', 'Analytics'],
                    'projects' => ['Lead generation funnel', 'Campaign dashboard'],
                ],
            ],
            [
                'name' => 'خالد عمر',
                'email' => 'student-demo-06@computiq.test',
                'phone' => '+964-770-100-0006',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Technology',
                    'department' => 'Computer Engineering',
                    'degree' => 'BSc',
                    'start_year' => 2019,
                    'graduation_year' => 2023,
                    'academic_status' => 'Graduate',
                    'headline' => 'Full Stack Developer',
                    'short_bio' => 'أبني تطبيقات تعليمية وتجارية من الواجهة إلى الخادم.',
                    'city' => 'Baghdad',
                    'country' => 'Iraq',
                    'preferred_role' => 'Full Stack Developer',
                    'preferred_city' => 'Baghdad',
                    'job_available' => true,
                    'internship_available' => false,
                    'linkedin_url' => 'https://linkedin.com/in/khaled-omar-computiq',
                    'github_url' => 'https://github.com/khaled-omar-computiq',
                    'portfolio_url' => 'https://khaled-omar-computiq.test',
                    'skills' => ['Laravel', 'React', 'Docker'],
                    'projects' => ['Hiring portal', 'Course marketplace'],
                ],
            ],
            [
                'name' => 'نورة سالم',
                'email' => 'student-demo-07@computiq.test',
                'phone' => '+964-770-100-0007',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Kufa',
                    'department' => 'English Language',
                    'degree' => 'BA',
                    'start_year' => 2022,
                    'graduation_year' => 2026,
                    'academic_status' => 'Junior',
                    'headline' => 'Communication Trainer',
                    'short_bio' => 'مهتمة بمهارات التواصل والإلقاء والعمل الجماعي.',
                    'city' => 'Najaf',
                    'country' => 'Iraq',
                    'preferred_role' => 'Training Coordinator',
                    'preferred_city' => 'Baghdad',
                    'job_available' => false,
                    'internship_available' => true,
                    'linkedin_url' => 'https://linkedin.com/in/noura-salem-computiq',
                    'github_url' => 'https://github.com/noura-salem-computiq',
                    'portfolio_url' => 'https://noura-salem-computiq.test',
                    'skills' => ['Public Speaking', 'Workshop Facilitation', 'Content Writing'],
                    'projects' => ['Student club workshops', 'Presentation coaching'],
                ],
            ],
            [
                'name' => 'هدى محمود',
                'email' => 'student-demo-08@computiq.test',
                'phone' => '+964-770-100-0008',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'Tikrit University',
                    'department' => 'Computer Science',
                    'degree' => 'BSc',
                    'start_year' => 2021,
                    'graduation_year' => 2025,
                    'academic_status' => 'Senior',
                    'headline' => 'QA Engineer',
                    'short_bio' => 'أحب اختبار المنتجات وتحسين الجودة والتجربة.',
                    'city' => 'Tikrit',
                    'country' => 'Iraq',
                    'preferred_role' => 'QA Engineer',
                    'preferred_city' => 'Erbil',
                    'job_available' => true,
                    'internship_available' => true,
                    'linkedin_url' => 'https://linkedin.com/in/huda-mahmoud-computiq',
                    'github_url' => 'https://github.com/huda-mahmoud-computiq',
                    'portfolio_url' => 'https://huda-mahmoud-computiq.test',
                    'skills' => ['Manual Testing', 'Postman', 'Test Cases'],
                    'projects' => ['Regression checklist', 'Checkout QA suite'],
                ],
            ],
            [
                'name' => 'أمير حسن',
                'email' => 'student-demo-09@computiq.test',
                'phone' => '+964-770-100-0009',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Duhok',
                    'department' => 'Information Systems',
                    'degree' => 'BSc',
                    'start_year' => 2020,
                    'graduation_year' => 2024,
                    'academic_status' => 'Graduate',
                    'headline' => 'Project Coordinator',
                    'short_bio' => 'مهتم بإدارة المشاريع والعمليات وتنسيق الفرق.',
                    'city' => 'Duhok',
                    'country' => 'Iraq',
                    'preferred_role' => 'Project Coordinator',
                    'preferred_city' => 'Erbil',
                    'job_available' => true,
                    'internship_available' => false,
                    'linkedin_url' => 'https://linkedin.com/in/amir-hassan-computiq',
                    'github_url' => 'https://github.com/amir-hassan-computiq',
                    'portfolio_url' => 'https://amir-hassan-computiq.test',
                    'skills' => ['Project Planning', 'Agile', 'Documentation'],
                    'projects' => ['Capstone planning board', 'Delivery workflows'],
                ],
            ],
            [
                'name' => 'فاطمة أحمد',
                'email' => 'student-demo-10@computiq.test',
                'phone' => '+964-770-100-0010',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Babylon',
                    'department' => 'Artificial Intelligence',
                    'degree' => 'BSc',
                    'start_year' => 2021,
                    'graduation_year' => 2025,
                    'academic_status' => 'Senior',
                    'headline' => 'ML Engineer',
                    'short_bio' => 'أعمل على نماذج تعلم آلي وتطبيقات ذكاء اصطناعي عملية.',
                    'city' => 'Hilla',
                    'country' => 'Iraq',
                    'preferred_role' => 'ML Engineer',
                    'preferred_city' => 'Baghdad',
                    'job_available' => true,
                    'internship_available' => true,
                    'linkedin_url' => 'https://linkedin.com/in/fatima-ahmed-computiq',
                    'github_url' => 'https://github.com/fatima-ahmed-computiq',
                    'portfolio_url' => 'https://fatima-ahmed-computiq.test',
                    'skills' => ['Machine Learning', 'PyTorch', 'Prompt Engineering'],
                    'projects' => ['Arabic sentiment model', 'LLM prompt library'],
                ],
            ],
            [
                'name' => 'عمر فؤاد',
                'email' => 'student-demo-11@computiq.test',
                'phone' => '+964-770-100-0011',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'Al-Mustansiriya University',
                    'department' => 'Accounting',
                    'degree' => 'BSc',
                    'start_year' => 2019,
                    'graduation_year' => 2023,
                    'academic_status' => 'Graduate',
                    'headline' => 'Business Analyst',
                    'short_bio' => 'أربط بين التحليل التجاري والمنتجات التقنية والتعليمية.',
                    'city' => 'Baghdad',
                    'country' => 'Iraq',
                    'preferred_role' => 'Business Analyst',
                    'preferred_city' => 'Baghdad',
                    'job_available' => true,
                    'internship_available' => false,
                    'linkedin_url' => 'https://linkedin.com/in/omar-fouad-computiq',
                    'github_url' => 'https://github.com/omar-fouad-computiq',
                    'portfolio_url' => 'https://omar-fouad-computiq.test',
                    'skills' => ['Business Analysis', 'Excel', 'Reporting'],
                    'projects' => ['Course ROI model', 'Operations reporting'],
                ],
            ],
            [
                'name' => 'لينا عباس',
                'email' => 'student-demo-12@computiq.test',
                'phone' => '+964-770-100-0012',
                'locale' => 'ar',
                'profile' => [
                    'university' => 'University of Baghdad',
                    'department' => 'Translation',
                    'degree' => 'BA',
                    'start_year' => 2022,
                    'graduation_year' => 2026,
                    'academic_status' => 'Junior',
                    'headline' => 'Content Specialist',
                    'short_bio' => 'أهتم بصناعة المحتوى التعليمي المحلي وترجمته وتحسينه.',
                    'city' => 'Baghdad',
                    'country' => 'Iraq',
                    'preferred_role' => 'Content Specialist',
                    'preferred_city' => 'Remote',
                    'job_available' => false,
                    'internship_available' => true,
                    'linkedin_url' => 'https://linkedin.com/in/lina-abbas-computiq',
                    'github_url' => 'https://github.com/lina-abbas-computiq',
                    'portfolio_url' => 'https://lina-abbas-computiq.test',
                    'skills' => ['Localization', 'Content Editing', 'Research'],
                    'projects' => ['Arabic glossary', 'Course copy refresh'],
                ],
            ],
        ];

        foreach ($students as $student) {
            $user = User::updateOrCreate(
                ['email' => $student['email']],
                [
                    'name' => $student['name'],
                    'real_name' => $student['name'],
                    'password' => Hash::make('password'),
                    'phone' => '+'.preg_replace('/\D+/', '', $student['phone']),
                    'country_code' => $student['country_code'] ?? 'IQ',
                    'locale' => $student['locale'],
                    'active_role' => 'student',
                    'is_active' => true,
                    'email_verified_at' => now(),
                ]
            );

            $user->ensureDefaultAppRole();

            StudentProfile::updateOrCreate(
                ['user_id' => $user->id],
                $student['profile']
            );
        }
    }
}
